### ISSUE TITLE
Adding configs for mana tablet and (greater) mana band capacity

### ISSUE THREAD

**Issue by anoomolu** [KonSola5/BotaniaConfigurator#3]
**What would you like to be included in Botania Configurator?**
Would be cool to have a similar level of configurability for portable mana storage options (Mana Tablet/ (Greater) Band of Mana). My use case is gutting pools overall and trying to bring back a diluted pool meta so you can't just afk with a patch of endoflames.

A question somewhat adjacent to above:
- Would it be out of scope for this mod to add mechanics? I was thinking like the runic altar progress slowly ticking backwards if not supplied with mana for a while.

**Comment by KonSola5** [comment]
Well, this mod already adds custom mechanics (like random Spectrolus color, the ability for every generating flower to decay) so this isn't out of scope at all.

**Comment by KonSola5** [comment]
I won't promise anything about the Runic Altar, because:
- I don't think this would change much in gameplay,
- This would require a ton of overwriting in the Runic Altar's class (depending on what behavior you would like to be implemented, whether it's draining mana only when the Altar didn't get Mana in the "charging" phase, or also in the "ready to craft" phase).
